### ISSUE TITLE
Modify sky map gallery to include pictures of transients

### ISSUE THREAD

**Issue by abunickabhi** [AshishMahabal/ZARTHalphafeedback#10]
The current Gallery opens to stock sky map objects like planets and galaxies. It would be better if the user can explore nice and crisp optical images that we have of transient explosions like supernovae and kilonovae.

**Comment by AshishMahabal** [comment]
That is indeed a future feature. Thanks!

**Comment by AshishMahabal** [comment]
@abunickabhi : This has been implemented by @Dhyey-Thummar
