### ISSUE TITLE
Guided write-up for the past "time travel" mode

### ISSUE THREAD

**Issue by abunickabhi** [AshishMahabal/ZARTHalphafeedback#11]
When the user wishes to time travel in the past to a skymap of the past, we can have a write-up enumerating key things that were observed then and can be re-looked by the user.

**Comment by AshishMahabal** [comment]
Time travel mode is from sky map. We are leaving it in, but may not include transients in that mode. Right now the plan is to have only one set of transients loaded in ZARTH.

**Comment by abunickabhi** [comment]
Okay one set of transient is a better idea. Time travel mode can be hidden.
