### ISSUE TITLE
Suggestive search function on the top

### ISSUE THREAD

**Issue by abunickabhi** [AshishMahabal/ZARTHalphafeedback#12]
The first time user would not know what to search for when they click on the search bar.

A suggestion like entering the letter 't' can be popped up, so that the user knows the right kind of objects to look out for.

**Comment by AshishMahabal** [comment]
Cool idea. A starting pop-up is a feature we have planned. Including a pop-up for a first time user would indeed be nice.

**Comment by AshishMahabal** [comment]
This has now been added by @Dhruv-Pindawala . It is also available through ZARTH Guide, a drop-down menu item.
