### ISSUE TITLE
Show the score / goal of user on the top right of the main screen

### ISSUE THREAD

**Issue by abunickabhi** [AshishMahabal/ZARTHalphafeedback#14]
It would be inconvenient for the user to keep on checking the leader board if they are on a mission or want to hunt upto a score.

It would be a good enhancement to have the score displayed on the top right like most games.

**Comment by AshishMahabal** [comment]
Something definitely worth considering.

**Comment by AshishMahabal** [comment]
This has been done (by @Dhyey-Thummar) as a daily score/credits remaining counter, @abunickabhi

**Comment by abunickabhi** [comment]
Okay got it!
