### ISSUE TITLE
Clippy like help pop-ups

### ISSUE THREAD

**Issue by abunickabhi** [AshishMahabal/ZARTHalphafeedback#7]
For a user to be able to engage and make a plan to continue catching transients, there should be a suggestive bot that can pop up and point to the next set of actions that can be taken.

This would lead to longer engagement.

**Comment by AshishMahabal** [comment]
One version of this has been implemented by @Dhyey-Thummar. Need to decide what frequency works best.

**Comment by Dhyey-Thummar** [comment]
For now, the frequency is that it will appear randomly every 2 or every 3 or every 4 times, a transient has been caught successfully.

**Comment by AshishMahabal** [comment]
For now that looks good. May want to consider tweaking frequency based on rarity, and adding additinal quotes per category.
